### ISSUE TITLE
MSF values are rewritten while generating EDC/ECC

### ISSUE THREAD

**Issue by jonblau** [alex-free/edcre#1]
This is probably a good thing in general, however, it becomes problematic in my use case, as I only wanted to add the missing EDC/ECC data on 150 "blank sectors" that only contained correct header data.
Since these sectors are meant to be part of the last data track pregap of a Dreamcast GD-ROM image, working around the issue involves creating from scratch then regenerating ~80-90 minutes of such sectors (unless I'm missing something).

An option to prevent edcre from updating MSF would be way more efficient in that situation.

PS: thanks for this already very good program!

**Comment by alex-free** [comment]
Can you go a bit more in depth of what you're doing with an example? What is expected, and what the program outputs would help.

Another feature I've wanted to add that may be related is to specify only a list of arbitrary sectors to look at/update EDC/ECC.

**Comment by jonblau** [comment]
Yes sure.

For example, if I try to process only 2 seconds/150 sectors which first sector is :
      00 FF FF FF FF FF FF FF FF FF FF 00 61 56 12 01
      00 ... etc without EDC/ECC
using the simple command ./edcre "pregap"

then opening "pregap" again with an hex editor shows that it now starts with :
      00 FF FF FF FF FF FF FF FF FF FF 00 00 02 00 01
      00 ... etc with EDC/ECC

while this result was expected :
      00 FF FF FF FF FF FF FF FF FF FF 00 61 56 12 01
      00 ... etc with EDC/ECC

Here's what program prints on the terminal:

EDCRE v1.0.6 - EDC/ECC Regenerator By Alex Free
https://alex-free.github.io/edcre
Made Possible By Modifying CDRDAO (GPLv2) Source Code:
https://github.com/cdrdao/cdrdao

Scanning LBA 300
Updated EDC/ECC in 150 sectors



And in case it may help, the workaround I found for this particular pregap that gives the expected result is :
./edcre -s 278562 "big_pregap"
"big_pregap" being 278712 sectors long (null data + the initial 150 sectors pregap)

with this output on the terminal:

EDCRE v1.0.6 - EDC/ECC Regenerator By Alex Free
https://alex-free.github.io/edcre
Made Possible By Modifying CDRDAO (GPLv2) Source Code:
https://github.com/cdrdao/cdrdao

Custom Sector Start For EDC/ECC Regen Enabled
Starting EDC/EEC Regeneration at LBA 278712 (0x270D3860)
Scanning LBA 278862
Updated EDC/ECC in 150 sectors



Tell me if you need more info.

**Comment by jonblau** [comment]
About the other feature you mentioned, I guess it could be related if edcre was able to rely on the MSF to determine in which sector it is reading/updating EDC/ECC. If it relies on the size of the file/track, it won't probably make a difference.

**Comment by alex-free** [comment]
That was interesting to implement. I think this does what you want. Use one of the attached betas and specify the new  -k argument in your ezre command. I.e. 

ezre -k youfilesnippet.bin

For any ezre commands using a file snippet like yours, you need to specify -k. So like

ezre -k -t youfilesnippet.bin 

will test the file snippet for any invalid EDC/ECC in the future. But once you add it to the final dreamcast image you don't need to use -k anymore (since it is a valid full disc image).

Let me know if this works or if you have questions. I did a small test and it looks like it works as expected.

[edcre-v1.0.7beta-linux-x86_64_static.zip](https://github.com/user-attachments/files/16091686/edcre-v1.0.7beta-linux-x86_64_static.zip)
[edcre-v1.0.7beta-linux-x86_static.zip](https://github.com/user-attachments/files/16091687/edcre-v1.0.7beta-linux-x86_static.zip)
[edcre-v1.0.7beta-windows-x86.zip](https://github.com/user-attachments/files/16091688/edcre-v1.0.7beta-windows-x86.zip)
[edcre-v1.0.7beta-windows-x86_64.zip](https://github.com/user-attachments/files/16091689/edcre-v1.0.7beta-windows-x86_64.zip)

**Comment by jonblau** [comment]
I can confirm the linux x86-64 build works perfectly now for that matter with edcre -k file, well done! This is a huge improvement for me, since I mainly use it through a 900 lines bash script that used to spend 70% of its time working around the issue.

So thank you Alex!

**Comment by alex-free** [comment]
> I can confirm the linux x86-64 build works perfectly now for that matter with edcre -k file, well done! This is a huge improvement for me, since I mainly use it through a 900 lines bash script that used to spend 70% of its time working around the issue.
> 
> So thank you Alex!

Great! I posted a new update (v1.0.7) with the feature. There is also .deb package files you can use on Linux now available.

What does that 900-line bash script do? Very curious.

**Comment by jonblau** [comment]
Nice, I'll try the .deb package too.

Well it performs several tasks on GD-ROM dumps made with DCSDRIP, mainly : integrity check, rom renaming, format conversion (pregap and offset correction compliant to redump).
